# BIG-IP Environment
location = "eastus"
AllowedIPs = ["0.0.0.0/0"]
github_owner = "f5devcentral"
github_token = "3"
bigip_count = 1
workload_count = 2
bigip_min = 1
bigip_max = 5
workload_min = 1
workload_max = 5
scale_interval = 300
repo_path = "/repos/f5devcentral/adc-telemetry-based-autoscaling/dispatches"